aquasecurity/windows-bench

cfg/1.1.0/definitions.yaml

chore: update description

---

README.md

doc: add example

---

go.mod
go.sum

chore: bump common bench

---

README.md
cfg/1.1.0/definitions.yaml

feat: add password check

---

.goreleaser.yml

chore: goreleaser cleanup

---

README.md

docs: add json output example

---

README.md

doc: add snapshot badge

---

README.md

doc: organized readme sections

doc: organized readme sections

---

.goreleaser.yml
cfg/2.0.0/definitions.yaml
docs/README.md
shell/powershell.go
shell/powershell_test.go

test: shell util

---

cfg/2.0.0/definitions.yaml

feat: admin lockout policy

---

cmd/app_test.go
cmd/util_test.go

test: run check and controls

---

cmd/root.go
main.go

feat: expose stdout stderr

---

cfg/2.0.0/definitions.yaml
cmd/root.go
cmd/util_test.go

fix: stdout and stderr

---

cmd/app.go
cmd/app_test.go
cmd/util.go
cmd/util_test.go

fix: error support

---

cfg/2.0.0/definitions.yaml

This PR adds policies for System Services.
The result with default settings:
The result after set up the policy for DC:

feat: add checks for System Services

---

cfg/2.0.0/definitions.yaml

This PR adds checks for Domain, Private and Public Profiles policies.

feat: add checks for Domain, Private and Public Profiles policies

---

cfg/2.0.0/definitions.yaml

This PR adds checks for Advanced Audit Policy Configuration.
This section contains recommendations for configuring the Windows audit facilities:
17.1 Account Logon
17.2 Account Management
17.3 Detailed Tracking
17.4 DS Access
17.5 Logon/Logoff
17.6 Object Access
17.7 Policy Change
17.8 Privilege Use
17.9 System

feat: add checks for Advanced Audit Policy Configuration

---

README.md

docs: remove `in progress` comment

docs: remove in progress comment

---

.github/workflows/build.yml
.github/workflows/release.yml
makefile

chore: add go mod tidy

---

go.mod
go.sum

chore: remove unicode chars

---

go.mod

chore: update go db

---

cmd/util.go

fix: update audit command update

---

cfg/2.0.0/definitions.yaml
cmd/util.go
cmd/util_test.go
shell/powershell.go

fix: detect server type

---

shell/powershell.go

fix: supress errors if command return error due to misconfig value

fix: supress errors if command return error due to misconfig value

---

go.mod

chore: update sum-db
